---
- name: toto.txt
  hosts: first
  remote_user: root

  tasks:
  - name: create empty toto.txt file
    ansible.builtin.file:
      path: /etc/toto.txt
      state: touch

  - name: install needed packages
    ansible.builtin.apt:
      name: cowsay
      state: present
      update_cache: yes

  - name: lance un cowsay 
    ansible.builtin.shell:
      cmd: cowsay "hello DevOps"
