---
- name: toto.txt
  hosts: first
  remote_user: root

  roles:
    - apaches2
    - mariadb


  tasks:
  - name: create empty toto.txt file
    ansible.builtin.file:
      path: /etc/toto.txt
      state: touch


