version: "3.8"
services:
  ssh-server:
    image: alpine
    container_name: 'ssh1-server'
    command: ["sh", "-c", "while true; do sleep 1; done"]
    restart: always
    ports:
      - 22:22
    networks:
      - backend_services
  ssh-client:
    image: alpine
    container_name: 'ssh2-client'
    command: ["sh", "-c", "while true; do sleep 1; done"]
    restart: always
    ports:
      - 21:22
    networks:
      - backend_services

networks:
  backend_services:
    driver: bridge