global:
  # Configuration globale pour Prometheus
        # Fréquence par défaut pour scruter les cibles
    scrape_interval: 15s
        # Fréquence par défaut pour évaluer les règles
    evaluation_interval: 15s

    # Configuration pour la collecte des métriques de cAdvisor
scrape_configs:
  - job_name: 'cadvisor'  # Nom du job
    static_configs:
    - targets:
      - cadvisor:80  # Remplacez par l'hôte et le port réels de cAdvisor

