global:
  # Configuration globale pour Prometheus
        # Fréquence par défaut pour scruter les cibles
    scrape_interval: 55s
        # Fréquence par défaut pour évaluer les règles
    evaluation_interval: 55s

    # Configuration pour la collecte des métriques de cAdvisor
scrape_configs:
  - job_name: 'cadvisor'  # Nom du job
    static_configs:
    - targets:
      - http://cadvisor:80  # Remplacez par l'hôte et le port réels de cAdvisor

  
    # Configuration pour la collecte des métriques de Prometheus
  - job_name: 'prometheus'  # Nom du job
    scrape_interval: 55s
    static_configs:
    - targets: 
      - http://prometheus:9090

