version: "3.7"
services:
  store-front:
    container_name: 'store-front'
    image: benjaminmelki/store-front-test
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend_services
networks:
  backend_services:
    driver: bridge