version: "3.7"
services:
  aks-store-demo-order-service:
    container_name: 'order-service'
    image: aks-store-demo-order-service
    ports:
      - 3000:3000
    networks:
      - backend_services
  store-front:
    container_name: 'store-front'
    image: benjaminmelki/store-front-test
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend_services
  product-service:
    container_name: 'product-service'
    image: aks-store-demo-product-service
    restart: always
    ports:
      - 3002:3002
    networks:
      - backend_services
networks:
  backend_services:
    driver: bridge