name: suprime le cluster azure
on:
  push:


env:
  nomcluster: nomcluster
  nom-grouperessource: grouperessource

jobs:
  clusterdestoy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
        uses: actions/checkout@v4.1.7

      - name: Login to docker Container Registry
        uses: docker/login-action@v3.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test
        env:
          # git diff pour savoir si on doit build ou pas
          hashFiles: git diff --name-only HEAD^ HEAD
        if: ${{ env.hashFiles }} != ''
        uses: docker/build-push-action@v6.4
        with:    
          tags: |
            ${{ env.image-product }}
          context: ./product-service
          platforms: ${{ env.platforms }}
          push: true
      
