name: build test
on:
  push:


env:
  nomcluster: nomcluster
  nom-grouperessource: grouperessource

jobs:
  clusterdestoy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout  
        uses: actions/checkout@v4.1.7

      - name: Build and push test
        run: |
          pip install localai 

      
      - name: Generate code with LocalAI
        run: |
          python -m localai generate --query "Génère moi le dev front d'un magasin de jouet."
        id: localai_output

      
