name: projet contoso local sans kubernetes
on: 
#  push:
  workflow_dispatch:

jobs:
  store-front:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: changes 
        with: 
          filters: | 
            store-front:
              - 'store-front/**'
      - name: docker build
        if: steps.changes.outputs.store-front == 'true'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test store-front
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.changes.outputs.store-front == 'true'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test

  product-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dorny/paths-filter@v3.0.2
        id: changes 
        with: 
          filters: | 
            product-service:
              - 'product-service/**'
      - name: docker build
        if: steps.changes.outputs.product-service == 'true'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2 product-service
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.changes.outputs.product-service == 'true'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2

  infrastructure:
    runs-on: self-hosted
    steps:
      - name : docker version
        run: docker --version

      - name: docker-compose version
        run: docker compose version

  monitoring:
    runs-on: self-hosted
    needs: [infrastructure]
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: main
          sparse-checkout: compose/docker-compose-monitoring.yml

      - name: ls
        run: ls 

      
        
      - name: docker-compose up 
        if: github.event_name == 'workflow_dispatch'
        run: |
           $path = "compose/docker-compose-monitoring - Copie.yml"
           (Get-Content $path) \ 
              -replace "$tagcompose","grafana/grafana:$latestTag" \ 
              -replace "prom/prometheus:v2.48.0","prom/prometheus:v2.48.0" \
              -replace "cadvisor:v0.47.2","cadvisor:v0.47.2"
              | Set-Content $path
           
           $path2 = ".\Desktop\devops\github action\test github action\github-action-test\compose\docker-compose-monitoring33.yml"           
           [System.IO.File]::WriteAllText($path2, ([System.IO.File]::ReadAllText($path2) \ 
             -replace $tagcompose, 'grafana/grafana:$latestTag'
             -replace prom/prometheus:v2.48.0, 'prom/prometheus:v2.48.0' \
             -replace cadvisor:v0.47.2, 'cadvisor:v0.47.2'))

      - name: install apli monitoring prometheus grafana
        run: |
          docker compose -f ./compose/docker-compose-monitoring.yml up -d
 
  contoso:
    runs-on: self-hosted
    needs: [infrastructure]
    steps:
      - uses: actions/checkout@v4
      - name: Create Application Contoso
        run: |
          docker compose -f ./compose/docker-compose-contoso.yml up -d
          