name: Test de Push

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: install de vialdi
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S -n apt install redis
    - name: affiche une vache qui dit que le push a marcher.
      run: |  
        cowsay "Le push vers le depot distant est une reussite totales et a bien installer le programme redis !"