name: Test de Push

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: confirmation Run push
      run: |
        wget -qO- https://repo.vivaldi.com/archive/linux_signing_key.pub | echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-key add -
        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S add-apt-repository 'deb https://repo.vivaldi.com/archive/deb/ stable main'
    - name: install de vialdi
      run: |
        sudo apt update && sudo apt install vivaldi-stable
    - name: affiche une vache
      run: |  
        cowsay "Le push vers le depot distant est une reussite totales de chez totale !"