name: Test de Push

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploiement:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: confirmation Run push
      run: |
       cowsay "Le push vers le depot distant est reussie !"