name: test g
on: 
  push:
    branches: main

jobs:
    job1:
        runs-on: self-hosted
        steps:
        - name: date
          run: date
        
        - name: test
          run: mkdir test
        
        - name: cowsay
          run: sudo apt install -y cowsay 

        - name: cowsay2 
          run: sudo mv /usr/share/cowsay /apps