name: test g
on: 
  push:
    branches: main

jobs:
    job1:
        runs-on: self-hosted
        steps:
        - name: date
          run: date
        
        - name: date
          run: echo 'test' >> sudo /apps/test

        - name: test
          run: ls /apps
        