name: configuration conteneur

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push, workflow_dispatch]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: donne la date pour test
      run: date

    #- name: copie de etc ansible 
    #  run: cp -r etc /home/ben/Bureau/ansible
    
    #- name: copie de playbook ansible
    #  run: cp -r playbook /home/ben/Bureau/ansible

    #- name: execution de la configuration de yml ansible
    #  run: ansible-playbook /home/ben/Bureau/ansible/playbook/recette.yml -v

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: installation dependance
      run: pip install -r requirements.txt

    - name: lance le script python
      run: python3 script.py

    - name: test 2l
      run: cp -r script.py /home/benjamin/toto/
