name: configuration conteneur

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push, workflow_dispatch]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy1:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: donne la date pour test
      run: date

    #- name: copie de etc ansible 
    #  run: cp -r etc /home/ben/Bureau/ansible
    
    #- name: copie de playbook ansible
    #  run: cp -r playbook /home/ben/Bureau/ansible

    #- name: execution de la configuration de yml ansible
    #  run: ansible-playbook /home/ben/Bureau/ansible/playbook/recette.yml -v

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: installation dependance
      run: pip install -r requirements.txt

    - name: lance le script python
      run: python3 script.py

    - name: copie de script
      run: cp script.py /home/benjamin
    
  mkdocs:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: installation dependance
      run: pip install -r requirements.txt

    - name: install mkdocs
      run: pip install mkdocs

    - name: copy2
      run: cp -r monprojet/monprojet/* .

#    - name: dev mkdocs 1
#      run: mkdocs serve -a 0.0.0.0:80 &

#    - name: arret
#      run: ls

    - name: caddy
      run: |
        sudo apt update
        sudo apt install -y caddy

    - name: copie de build
      run: mkdocs build

    - name: copie de deploiement
      run: cp site /usr/share/caddy/

    needs: deploy1