name: exo3 self-hosted
on: 
  push:
    branches: main

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: date
          run: date

        - name: date 2
          run: wget https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
        
        - name: date 3
          run: tar -xvf cowsay_2.0.4_Linux_x86_64.tar.gz

        - name: date 4
          run: ls -alh

        - name: date 4
          run: ./cowsay test

        - name: output the message on actions result
          uses: Code-Hex/neo-cowsay-action@v1
          with:
            message: | # Support multi-lines
              This is cowsay
              Hello, World!!

        - name: cowsay on the comment
          uses: Code-Hex/neo-cowsay-action@v1
          with:
             message: 'Hello, World with random'
             cow: 'random' # If specified, it shows random ascii art.
             cowsay_on_comment: true