name: build test 4
on: 
  push:
  workflow_dispatch:

jobs:
  ohello_world_jb1:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test store-front
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test

  ohello_world_jb2:
    runs-on: ubuntu-latest
    env: 
      test: git diff --name-only
      test2: cat changed-files.txt
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - run: git log --oneline 
      - run: git diff --name-only
      - run: git rev-parse HEAD~1
      - run: git rev-parse HEAD
      - run: |
          BASE_COMMIT=$(git rev-parse HEAD~1) 
          HEAD_COMMIT=$(git rev-parse HEAD) # Comparer les commits et lister les fichiers modifiés 
          git diff --name-only $BASE_COMMIT $HEAD_COMMIT > changed-files.txt || true 
      - run: cat changed-files.txt
      - name: docker build
        if: ${{ env.test }} = "production"
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2 product-service
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2
      
