name: build test 4
on: 
  push:
#  workflow_dispatch:

env:
  dex: docker exec kubectl sh -c

jobs:
  store-front:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: changes 
        with: 
          filters: | 
            store-front:
              - 'store-front/**'
      - name: docker build
        if: steps.changes.outputs.store-front == 'true'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test store-front
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.changes.outputs.store-front == 'true'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/store-front-test

  product-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dorny/paths-filter@v3.0.2
        id: changes 
        with: 
          filters: | 
            product-service:
              - 'product-service/**'
      - name: docker build
        if: steps.changes.outputs.product-service == 'true'
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2 product-service
      - run: docker image ls
      - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - if: steps.changes.outputs.product-service == 'true'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/product-service-test2

  setup_k3s:
    runs-on: self-hosted
    steps:
      - name: verif si container k3s-server existe sur win 
        run: docker ps -a | findstr k3s-server 
        id: k3s-server
        continue-on-error: true

      - if: steps.k3s-server.outcome == 'failure'
        name: setup k3s dans docker
        run: |
          docker run -d --name k3s-server --network k3s --privileged --restart=always -p 6443:6443 rancher/k3s:v1.31.0-k3s1 server 

  kubectl:
    runs-on: self-hosted
    needs: setup_k3s
    steps:
      - name: verif si container kubectl existe sur win
        run: docker ps -a | findstr kubectl 
        id: kubectl
        continue-on-error: true

      - name: setup kubectl
        if: steps.kubectl.outcome == 'failure'
        run: |
          echo "setup kubectl" \
          ; docker run -d -p 80:80 -p 8080:8080 -p 9090:9090 -p 3000:3000 -p 3002:3002 --network k3s --name kubectl alpine sh -c 'sleep infinity' \
          ; echo "setup kubectl terminé"
        continue-on-error: true

      - name: install kubectl
        run: |
          echo "install kubectl" 
          ; ${{ env.dex }} 'apk add kubectl --no-cache'
          ; echo "install kubectl terminer" 
          ; echo "creation du fichier de config kubectl" 
          ; ${{ env.dex }} 'mkdir -p /root/.kube/' 
          ; echo "creation du chemin de config kubectl terminer"
         
      - name: copie k3s.yaml kubectl
        run: |
          echo "copie du fichier de config k3s dans kubectl" 
          docker cp k3s-server:/etc/rancher/k3s/k3s.yaml . 
          docker cp k3s.yaml kubectl:/root/.kube/config 
          echo "copie du fichier de config k3s dans kubectl terminer"

      - name: met ip k3s-server dans une variable et modifie la config kubectl
        run: |
          echo "Recuperation l'ip du k3s-server." 
          ; IP=$(hostname -I | awk '{print $1}') || { echo "Erreur de récupération de l'IP." >&2; exit 1; } 
          ; echo "Recupération de l'ip terminé avec succès." 
          ; echo "Modification du fichier de config kubectl" 
          ; ${{ env.dex }} "sed -i 's/127.0.0.1/$IP/g' /root/.kube/config" || { echo "Erreur de modification du fichier de config kubectl." >&2; exit 1; } 
          echo "Modification du fichier de config kubectl terminé avec succes."

      - name: verif kubectl
        run: |
          echo "verif kubectl" \
          ; ${{ env.dex }} 'kubectl get nodes' \
          echo "verif kubectl terminer"

  monitoring:
    runs-on: self-hosted
    needs: kubectl
    steps:
      - name: verif si helm est installé
        run: ${{ env.dex }} 'helm'
        id: helm
        continue-on-error: true

      - name: installe helm 
        if: steps.helm.outcome == 'failure'
        run: |
          ${{ env.dex }} 'wget https://get.helm.sh/helm-v3.16.3-linux-amd64.tar.gz 
          ${{ env.dex }} tar -zxvf helm-v3.16.3-linux-amd64.tar.gz 
          ${{ env.dex }} mv linux-amd64/helm /usr/local/bin/helm 
          ${{ env.dex }} rm -rf linux-amd64 helm-v3.16.3-linux-amd64.tar.gz'

      - name: install helm apli monitoring
        run: |
          ${{ env.dex }} 'helm repo add prometheus-community https://prometheus-community.github.io/helm-charts \
          ${{ env.dex }} helm upgrade --install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 57.0.3 -n monitoring --create-namespace --timeout=35m'
  
      - name: attendre monitoring
        run: |
          ${{ env.dex }} 'kubectl wait --for=condition=available deployment --all -n monitoring --timeout=35m'
      
  argocd:
    runs-on: self-hosted
    needs: kubectl
    steps:
      - name: install curl
        run: |
          ${{ env.dex }} 'apk add curl --no-cache'

      - name: verif si argocd binaire existe deja
        run: ${{ env.dex }} 'argocd'
        id: argocd
        continue-on-error: true
        
      - name: install cli-argocd
        if: steps.argocd.outcome == 'failure'
        run: |
          ${{ env.dex }} 'curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.13.2/argocd-linux-amd64 
          ${{ env.dex }} install -m 555 argocd-linux-amd64 /usr/local/bin/argocd 
          ${{ env.dex }} rm argocd-linux-amd64'

      - name: create namespace argocd
        run: |
          ${{ env.dex }} 'kubectl get namespace argocd || kubectl create namespace argocd'

      - name: verif si argocd-server est en service
        run: ${{ env.dex }} 'kubectl get svc argocd-server -n argocd'
        id: argocd-server
        continue-on-error: true

      - name: Deploys application argocd
        run: | 
          ${{ env.dex }} 'kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.13.2/manifests/install.yaml -n argocd --timeout=35m' 

      - name: attendre argocd
        run: |
          ${{ env.dex }} 'kubectl wait --for=condition=available deployment --all -n argocd --timeout=35m'

#      - name: load balancing
#        run: |
#          echo '{"spec": {"type": "LoadBalancer"}}' > patch.json
#          kubectl patch svc argocd-server -n argocd --type merge --patch "$(cat patch.json)

      - name: connexion argocd
        if: steps.argocd-server.outcome == 'failure'
        env:
          ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: |
          ${{ env.dex }} 'kubectl port-forward svc/argocd-server -n argocd 80:80 &'
          sleep 10
          ${{ env.dex }} 'argocd login 127.0.0.1:80 --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure ${{ env.sensible-pas-afficher }}'
        continue-on-error: true
          
      - name: update ArgoCD password
        if: steps.argocd-server.outcome == 'failure'
        env:
          mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: ${{ env.dex }} 'argocd account update-password --account admin --new-password ${{ secrets.ARGOCD }} --current-password ${{ env.mdp }} ${{ env.sensible-pas-afficher }}'
        continue-on-error: true

  contoso:
    runs-on: self-hosted
    needs: [kubectl, argocd]
    steps:
      - name: Create Contoso namespace
        run: |
          ${{ env.dex }} 'kubectl get namespace contoso || kubectl create namespace contoso'
      
      - name: connexion argocd
        env:
            ip: kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
            mdp: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
        run: |
            ${{ env.dex }} 'kubectl port-forward svc/argocd-server -n argocd 80:80 &'
            sleep 5
            ${{ env.dex }} 'argocd login 127.0.0.1:80 --username admin --password ${{ secrets.ARGOCD }} --insecure ${{ env.sensible-pas-afficher }}'
        
      - name: Create Application Contoso with Argocd avec namespace
        run: ${{ env.dex }} 'argocd app create contoso --repo https://github.com/MelkiBenjamin/deploiement-apli-kubernetes-argocd --path ecommerce --dest-server https://kubernetes.default.svc --dest-namespace contoso --sync-policy automated --auto-prune'

