name: configuration conteneur

# Ici on déclare qu'on execute ce workflow si on fait un git push
on: [push, workflow_dispatch]

jobs:

  # Ici c'est notre premiere action, on pourrait en faire plusieurs
  deploy:

    # Ici on utiliser notre Runner déployé sur la vm server
    runs-on: self-hosted

    # Ici on déclare des actions à effectuer sur notre vm server    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: donne la date pour test
      run: date

    #- name: copie de etc ansible 
    #  run: cp -r etc /home/ben/Bureau/ansible
    
    #- name: copie de playbook ansible
    #  run: cp -r playbook /home/ben/Bureau/ansible

    #- name: execution de la configuration de yml ansible
    #  run: ansible-playbook /home/ben/Bureau/ansible/playbook/recette.yml -v

    - name: install python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Déplacer l'installation de Python
      run: |
        mv ${{ env.RUNNER_TOOL_CACHE }}/Python/3.11.7/x64 /usr/local/python
        if: env.RUNNER_TOOL_CACHE != '/usr/local/python'

    - name: Ajuster le chemin d'accès pour Python
      run: echo "PATH=$PATH:/usr/bin:/usr/local/bin" >> $GITHUB_ENV

    - name: Afficher le contenu du chemin d'accès
      run: echo $PATH

    - name: installation dependance
      run: pip install -r requirements.txt

    - name: lance le script python
      run: python3 script.py

    - name: test 2l
      run: cp -r /home/benjamin/actions-runner/toto /home/benjamin

    - name: Vérifier la version de Python
      run: |
        python --version
        python3 --version